[project]
name = "pro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi[standard]>=0.128.0",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "python-dotenv>=1.2.1",
    "python-jose[cryptography]>=3.5.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "aerich>=0.9.2",
    "ruff>=0.14.13",
    "tomli-w>=1.2.0",
    "tomlkit>=0.14.0",
]
prod = [
    "aerich>=0.9.2",
    "asyncpg>=0.31.0",
    "tortoise-orm>=0.25.3",
]

[tool.aerich]
tortoise_orm = "app.db.aerich_config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."
